name: diff-id
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print file path
        run: echo "{ENV_FILE}"
        env:
          ENV_FILE: ${{ env.GITHUB_ENV}}
