name: diff-id
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print env file path
        run: echo "${GITHUB_ENV}"

      - name: print env file content(initial value)
        run: cat "${GITHUB_ENV}"

      - name: add env var
        run: |
          echo "TEST1=var1" > "${GITHUB_ENV}"
