name: diff-id
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print env file path
        run: echo "GITHUB_ENV=${GITHUB_ENV}"

      - name: print env file content(initial value)
        run: echo "GITHUB_ENV=${GITHUB_ENV}"
        env:
