name: diff-id
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print env file path
        run: echo "${GITHUB_ENV}"

      - name: print env file content(initial value)
        run: |
          echo "--"
          cat "${GITHUB_ENV}"
          echo "--"

      - name: add env var
        run: |
          echo "--"
          echo "${TEST1}"
          echo "--"
          echo "TEST1=var1" > "${GITHUB_ENV}"
          echo "${TEST1}"
          echo "--"

      - name: print env var
        run: |
          echo "--"
          echo "${TEST1}"
          echo "--"
          echo "${TEST1_C}"
          echo "--"
        env:
          TEST1_C: ${{ env.TEST1}}
